providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1745885067'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = ['npm run build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_24',
    'npm-9_x',
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = '23f9169c4ccce521379e602cc82ed873a1f1b52b'

[start]
cmd = 'npm run start'

